baseURL = "https://zzp1012.github.io/"
languageCode = "en-us"
title = "Zhanpeng Zhou"
theme="archie"
copyright = "© Athul"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
publishdir = "./docs"
paginate=3 # articles per page

[params]
	mode="auto" # color-mode → light,dark or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/zzp1012/"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/zhanpeng_zhou/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3